import Head from 'next/head'
import AuthButton from '@/modules/auth/components/AuthButton'
import Publish from '../modules/publish/Publish'
import WatchCourse from '@/modules/watch-course/components/WatchCourse'

export const APP_VERSION = 'v1.0.0'

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Owlearn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex min-h-screen justify-start items-start">
          {/* <Publish /> */}
          {/* <AuthButton /> */}
          <WatchCourse
            cids={[
              'bafkreifami5tmfbt2glxioar5x7gbtm7wdswbcjans2lqy4ur6efrpwpua',
              'bafkreidxbfshubnuz32rzfo4op5nlmbhbt7tfsx2ztvpvtgrt5ow6ll6ii',
            ]}
          />
        </div>
      </main>
    </>
  )
}
